In [89]:
import numpy as np
import pandas as pd

# Q1. Pandas version

In [90]:
pd.__version__

'2.3.3'

In [91]:
data = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

In [92]:
import os

filename = data.split("/")[-1]

if os.path.exists(filename):
    print("File already exists.")
else:
    !wget $data


File already exists.


In [93]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [94]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# Q2. Records count

In [95]:
len(df)

9704

# Q3. Fuel Types

In [96]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [97]:
df.fuel_type.nunique()

2

# Q4. Missing values

In [98]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

In [99]:
df.origin.unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [100]:
max(df.fuel_efficiency_mpg[df.origin == 'Asia'])

23.759122836520497

# Q6. Median value of horsepower

In [101]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [102]:
df.horsepower.median()

np.float64(149.0)

In [103]:
mode = df.horsepower.mode()[0]
mode

np.float64(152.0)

In [104]:
df['horsepower'] = df.horsepower.fillna(mode)

In [105]:
df.horsepower.median()

np.float64(152.0)

# Q7. Sum of weights

In [106]:
X = np.array(df[['vehicle_weight', 'model_year']][df.origin == 'Asia'][:7])
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [107]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [108]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [109]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [110]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [111]:
w[0] + w[1]

np.float64(0.5187709081074016)